version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=vietduc2811
    volumes:
      - mongodb_data:/data/db

  backend:
    build: .
    container_name: backend
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    env_file:
      - .env
    volumes:
      - .:/app
    working_dir: /app
    command: npm start

volumes:
  mongodb_data:
